homework/hw7/task1/mysite/face_swap_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "face_swap_app"
urlpatterns = [
    path("", views.index, name="index"),
    path("result", views.result, name="result"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homework/hw7/task1/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("face_swap_app/", include("face_swap_app.urls")),
    path("admin/", admin.site.urls),
]

homework/hw7/task1/mysite/face_swap_app/models.py
from django.db import models


class Image(models.Model):
    image = models.ImageField(upload_to="images/")


class SurnameInput(models.Model):
    surname = models.TextField(max_length=50)

homework/hw7/task1/mysite/face_swap_app/forms.py
from django import forms

from .models import Image, SurnameInput


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ["image"]


class SurnametInputForm(forms.ModelForm):
    class Meta:
        model = SurnameInput
        fields = ["surname"]

homework/hw7/task1/mysite/face_swap_app/views.py
import os
import sys

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from django.urls import reverse

from .forms import ImageForm, SurnametInputForm

from .face_swap_src.main import swap_and_save_loaded_image


def index(request):
    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES)

        if form.is_valid():
            try:
                handle_uploaded_file(request.FILES)
            except RuntimeError:
                print(sys.exc_info()[1])
                error_message = (
                    "Your image does not contain face or contains more than one face. Please load another " "image. "
                )
                return render(request, "face_swap_app/index.html", {"form": form, "error_message": error_message})
            return HttpResponseRedirect(reverse("face_swap_app:result"))
    else:
        form = ImageForm()
    return render(request, "face_swap_app/index.html", {"form": form})


def handle_uploaded_file(files):
    items = list(list(files.items())[0])
    path = os.path.join("media", "images", "uploaded_image.jpg")
    with open(path, "wb+") as destination:
        for chunk in items[1].chunks():
            destination.write(chunk)
    swap_and_save_loaded_image()


def result(request):
    if request.method == "POST":
        form = SurnametInputForm(request.POST)

        if form.is_valid():
            answer = form.cleaned_data["surname"]
            if check_answer(answer):
                return render(request, "face_swap_app/result.html", {"form": form, "success": True})
            return render(request, "face_swap_app/result.html", {"form": form, "failure": True})
    else:
        form = SurnametInputForm()
        return render(request, "face_swap_app/result.html", {"form": form})


def check_answer(answer: str) -> bool:
    if answer.lower() == "putin":
        return True
    return False

homework/hw7/task1/mysite/face_swap_app/templates/face_swap_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Image load</title>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'face_swap_app/style.css' %}">
</head>
<body>
    <div>
        <div>
            You may wonder why you can upload only ONE image if the app's goal is to swap faces.
        </div>

        <div>
            But do it.
        </div>

        <div>
            You will get answers, just go further.
        </div>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Upload</button>
        </form>

        {% if error_message %}
            <div class="alert">
                {{ error_message }}
            </div>
        {% endif %}
    </div>
</body>
</html>

homework/hw7/task1/mysite/face_swap_app/templates/face_swap_app/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hotel Images</title>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'face_swap_app/style.css' %}">
</head>
<body>
    <div>
        {% if success %}
            <div>
                Congratulations! You did it! Here is your prize:
            </div>
        {% else %}
            <div>
                Here is a result of your photo face swapped with our hidden man:
            </div>
        {% endif %}

        {% if failure %}
            <div class="alert">
                I am sorry. You have to try again
            </div>
        {% endif %}
        <div class="images-container">
            <img src="media/images/uploaded_image.jpg" />
            {% if success %}
                <img src="media/images/FirstOnSecond.jpg" />
            {% endif %}
            <img src="media/images/SecondOnFirst.jpg" />
        </div>

        {% if success %}
            <a href="{% url 'face_swap_app:index' %}">Try again?</a>
        {% else %}
            <div>
                Your task now is to define who is a mysterious stranger. Enter his surname:
            </div>
            <form method = "post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
            <button type="submit">Upload</button>
        {% endif %}
    </form>
    </div>
</body>
</html>